kg_embedding_size: 64           # (int) The embedding size of the KG feature.
hidden_size: 64                # (int) The number of features in the hidden state.
dropout_prob: 0.1               # (float) The dropout rate.

loss_type: 'CE'                 # (str) The type of loss function. Range in ['BPR', 'CE'].
embedding_size: 64
freeze_kg: False
gamma: 10.0
#train_batch_size: 512


n_layers: 2                     # (int) The number of transformer layers in transformer encoder.
n_heads: 2                      # (int) The number of attention heads for multi-head attention layer.
inner_size: 256                 # (int) The inner hidden size in feed-forward layer.
hidden_dropout_prob: 0.1        # (float) The probability of an element to be zeroed.
attn_dropout_prob: 0.1          # (float) The probability of an attention score to be zeroed.
hidden_act: 'gelu'              # (str) The activation function in feed-forward layer.
layer_norm_eps: 1e-12           # (float) A value added to the denominator for numerical stability.
initializer_range: 0.02         # (float) The standard deviation for normal initialization.



n_factors: 4
ind: 'distance'
sim_regularity: 1e-4


lmd: 0.1
tau: 0.5
sim: 'dot'



load_col:
    inter: [user_id, item_id, rating, timestamp]
#    item: [item_id,movie_title,release_year,genre]
    kg: [head_id, relation_id, tail_id]
    link: [item_id, entity_id]
    ent_feature: [ent_id, ent_vec]
    rel_feature: [rel_id, rel_vec]
alias_of_entity_id: [ent_id]
alias_of_relation_id: [rel_id]
preload_weight:
    ent_id: ent_vec
    rel_id: rel_vec
additional_feat_suffix: [ent_feature, rel_feature]

eval_args:
    group_by: user
    order: TO
    split: {'RS': [0.8,0.1,0.1]}
    mode: full

topk: [1,5,10,20,50,100]
valid_metric: hit@5


train_stage: 'pretrain'         # (str) The training stage. Range in ['pretrain', 'finetune'].
pretrain_epochs: 3            # (int) The epochs of pre-training.
save_step: 1                   # (int) Save pre-trained model every pre-training epochs.
stopping_step: 10
epochs: 200
learning_rate: 0.001
gpu_id: 0
contrast: 'x'
MAX_ITEM_LIST_LENGTH: 50

# 新增
k_intention: 4
score_type: 'max'
